### ISSUE TITLE
Excluded files config is not honored

### ISSUE THREAD

**Issue by mdesantis** [misogi/vscode-ruby-rubocop#163]
The extension keeps running Rubocop on excluded files; for example, given the following `.rubocop.yml`:

```yml
AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - 'config/**/*'
```

I keep getting highlighted errors on `config/application.rb`:

![Schermata del 2022-02-11 21-19-34](https://user-images.githubusercontent.com/283320/153664295-c7380faa-157e-4127-a160-4faa2b812691.png)
